# Generated by Django 4.2.7 on 2023-11-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='about',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
