# Generated by Django 4.2.7 on 2023-11-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_fill_category_skills'),
        ('candidate', '0004_alter_candidate_about_alter_candidate_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.category',
            ),
        ),
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
