# Generated by Django 4.2.7 on 2023-12-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0003_fill_category_skills'),
        ('candidate', '0005_candidate_category_candidate_github_and_more'),
        ('recruiter', '0002_alter_recruiter_about_alter_recruiter_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                (
                    'candidates',
                    models.ManyToManyField(blank=True, to='candidate.candidate'),
                ),
                (
                    'category',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='core.category',
                    ),
                ),
                (
                    'recruiter',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='recruiter.recruiter',
                    ),
                ),
                ('skills', models.ManyToManyField(to='core.skill')),
            ],
        ),
    ]
