export const BASE_URL = "http://localhost:8000"
export const CANDIDATES_URL = "/api/candidates"
export const RECRUITERS_URL = "/api/recruiters"
export const GET_ACCESS_TOKEN = "/api/token/"
export const REFRESH_TOKEN = "/api/token/refresh/"