export const BASE_URL = "http://localhost:8000/api"
export const CANDIDATES_URL = "/candidates/"
export const RECRUITERS_URL = "/recruiters/"
export const GET_ACCESS_TOKEN = "/token/"
export const REFRESH_TOKEN = "/token/refresh/"
export const CATEGORIES_URL = "/shared/categories/"
export const SKILLS_URL = "/shared/skills/"
export const COUNTRIES_URL = "https://restcountries.com/v3.1/all?fields=name"