export const HOME = "/"
export const ABOUT = "/about"
export const SIGNUP = "/signup"
export const SIGNIN = "/signin"
export const PROFILE = "/profile"
export const RECOMMENDATIONS = "/recommendations"
export const VACANCIES = "/vacancies"
export const CANDIDATES = "/candidates"