# Generated by Django 4.2.7 on 2023-11-18 17:42

from django.db import migrations


def create_skills(apps, schema_editor):
    Skill = apps.get_model('core', 'Skill')
    skills = [
        'Python',
        'Django',
        'Flask',
        'JavaScript',
        'TypeScript',
        'Angular',
        'React',
        'Vue.js',
        'Node.js',
        'Express.js',
        'Java',
        'Spring Framework',
        'Hibernate',
        'C/C++',
        'Embedded',
        'Assembly',
        'C#',
        'HTML',
        'CSS',
        'SQL',
        'Ruby',
        'Swift',
        'Objective-C',
        'Perl',
        'Go',
        'R',
        'MATLAB',
        'Scala',
        'Kotlin',
        'Shell Scripting',
        'Ruby on Rails',
        'PHP',
        'Laravel',
        'WordPress',
        'Machine Learning',
        'Deep Learning',
        'Computer Vision',
        'Natural Language Processing',
        'Data Science',
        'TensorFlow',
        'PyTorch',
        'Keras',
        'Scikit-Learn',
        'Hadoop',
        'Spark',
        'DevOps',
        'AWS',
        'Azure',
        'Google Cloud',
        'Docker',
        'Kubernetes',
    ]
    Skill.objects.bulk_create([Skill(name=skill) for skill in skills])


def create_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    categories = [
        'Python',
        'JavaScript',
        'TypeScript',
        'Angular',
        'React',
        'Vue.js',
        'Java',
        'C/C++',
        'C#',
        'Ruby',
        'Swift',
        'Objective-C',
        'Perl',
        'Go',
        'R',
        'Scala',
        'Kotlin',
        'PHP',
        'Data Science',
        'Data Engineer',
        'Data Analyst',
        'DevOps',
    ]
    Category.objects.bulk_create([Category(name=category) for category in categories])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_category_skill'),
    ]

    operations = [
        migrations.RunPython(create_skills),
        migrations.RunPython(create_categories),
    ]
