# Generated by Django 4.2.7 on 2024-02-17 21:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_fill_category_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.image_upload_to),
        ),
    ]
